### PR TITLE
Reader view: Add ability to change CSS styles, migrate from Crux to Readability4J

### LINKED ISSUE #104: Bug: Reader view of previous entry may get loaded instead of selected entry's content
#### How to reproduce bug:
- Set view mode to reader view.
- Select an entry that takes a long time to load.
- While it is loading, select one or more other entries.
- The loaded content may be the reader view of the previous long-loading entry instead of the selected entry's content.

#### Log:
```
Mar 25, 2019 2:57:39 PM seedu.address.ui.BrowserPanel handleRunning
INFO: Loading file:///Users/Rayner/Documents/UNIVERSITY/CS2103T/main/data/articles/DMNMIF3SJHV74Q55JYX7VEJDOA======.html...
Mar 25, 2019 2:57:42 PM seedu.address.ui.BrowserPanel handleSucceeded
INFO: Successfully loaded file:///Users/Rayner/Documents/UNIVERSITY/CS2103T/main/data/articles/DMNMIF3SJHV74Q55JYX7VEJDOA======.html
Mar 25, 2019 2:57:42 PM seedu.address.ui.BrowserPanel handleRunning
INFO: Loading file:///Users/Rayner/Documents/UNIVERSITY/CS2103T/main/data/articles/5W2A5E76QKTLIVV52K3TSGRRJ4======.html...
Mar 25, 2019 2:57:43 PM seedu.address.ui.BrowserPanel handleRunning
INFO: Loading reader view for file:///Users/Rayner/Documents/UNIVERSITY/CS2103T/main/data/articles/5W2A5E76QKTLIVV52K3TSGRRJ4======.html...
Mar 25, 2019 2:57:43 PM seedu.address.ui.BrowserPanel handleSucceeded
INFO: Successfully loaded reader view for file:///Users/Rayner/Documents/UNIVERSITY/CS2103T/main/data/articles/5W2A5E76QKTLIVV52K3TSGRRJ4======.html
```
Note that "Loading reader view" must not appear directly after "Loading.." when running correctly - "Loading reader view" should only appear directly after "Successfully loaded".

### LINKED ISSUE #115: As a heavy user, I can change the reading view style
so that I can choose the style that helps me read large amount of content most comfortably in my lighting conditions.

### Part of epics:
- #27 Reader view

### PR DESCRIPTION
**Pull request by rlrh**
#### Summary of changes:
- Add ability to change CSS styles
  - `view reader s/[DEFAULT, SEPIA, DARK, BLACK]`
  - Change `ViewMode` from enum to class comprising `ViewType`, `ReaderViewStyle`
  - Add new CSS stylesheets
- Migrate from Crux to Readability4J
  - Remove Crux library and add Readability4J library to `build.gradle`
  - Modify `AddCommand` and `ReaderViewUtil` accordingly
- Improve behaviour of `BrowserPanel`
  - More rules on whether to load reader view
  - Add reader view failure error page
- Refactor code
  - Move Reader View generation to `ReaderViewUtil`

### CODE REVIEW

**Comment by thomastanck** [comment]
How hard is it to split this into 2 PRs?

**Comment by rlrh** [comment]
> How hard is it to split this into 2 PRs?

Hmm I think it won't be easy as I did the migration and refactor at the same time, the commits are kind of faked.

File: src/main/java/seedu/address/ui/util/ReaderViewUtil.java [hunk 1]
```diff
@@ -0,0 +1,267 @@
...
+     * @param article Readability4J article
+     * @return optional article metadata element
+     */
+    private static Optional<Element> createArticleMetadataElement(Document rawDocument, Article article) {
+
+        Element articleMetadataWrapperElement =
+                new Element(Tag.valueOf(DIV_TAG), "").addClass(METADATA_WRAPPER_STYLE_CLASS);
+
+        // add byline element if author(s) present
+        OptionalCandidate
```
Comment (thomastanck) [inline src/main/java/seedu/address/ui/util/ReaderViewUtil.java:150]: Really nice monadic code. Well done.

File: src/test/java/seedu/address/testutil/TypicalEntries.java [hunk 2]
```diff
@@ -298,21 +298,23 @@
...
             .withAddress("Browser panel test web page")
             .build();
-    public static final String BROWSER_PANEL_TEST_ENTRY_BASE_URL =
-            MainApp.class.getResource("/view/BrowserPanelTest/test.html").toExternalForm();
+    public static final String WIKIPEDIA_ENTRY_BASE_URL = "http://en.wikipedia.org/wiki/Therapsids";
     public static final Entry WIKIPEDIA_ENTRY = new EntryBuilder()
             .withTitle("Wikipedia Test Web Page")
             .withDescription("Wikipedia test web page")
-            .withLink(MainApp.class.getResource("/view/BrowserPanelTest/wikipedia.html").toExternalForm())
+            .withLink("file://" + MainApp.class.getResource("/view/BrowserPanelTest/wikipedia.html")
```
Comment (thomastanck) [inline src/test/java/seedu/address/testutil/TypicalEntries.java:314]: Why did we need to revert back to the triple file:/// slash? I thought we patched that particular Link validation regex.

**Review by thomastanck — COMMENTED** [review]
Just some comments on your PR. Looks very good so far.

File: src/main/java/seedu/address/ui/ReaderViewStyle.java [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+import java.net.URL;
+import java.util.Locale;
+
+import seedu.address.MainApp;
+
+/**
+ * Available reader view styles.
+ */
+public enum ReaderViewStyle {
+    DEFAULT(requireNonNull(MainApp.class.getResource(Constants.STYLESHEETS_FILE_FOLDER + "default.css"))),
```
Comment (epicfailname) [inline src/main/java/seedu/address/ui/ReaderViewStyle.java]: I think ```ReaderViewStyle.class.getResource(...)``` works, then don't need to import ```MainApp```

**Review by epicfailname — DISMISSED** [review]

File: src/test/java/seedu/address/testutil/TypicalEntries.java (hunk 2 above)
Comment (rlrh) [reply src/test/java/seedu/address/testutil/TypicalEntries.java:314]: It's because of this line in `BrowserPanel#handleSucceeded`:
```java
if (viewMode.getViewType().equals(ViewType.READER)
                && !hasLoadedReaderView
                && currentLocation.equals(webEngine.getLocation())) {
```
I added the last condition in an attempt to fix the bug #104. I'm not exactly sure how the bug happens but this seems to fix it so far.

File: src/main/java/seedu/address/ui/ReaderViewStyle.java (hunk 3 above)
Comment (rlrh) [reply src/main/java/seedu/address/ui/ReaderViewStyle.java]: Thanks, didn't know this could be done!

Comment (rlrh) [reply src/main/java/seedu/address/ui/ReaderViewStyle.java]: Fixed in 7ef2cc8

File: src/main/java/seedu/address/ui/util/ReaderViewUtil.java (hunk 1 above)
Comment (rlrh) [reply src/main/java/seedu/address/ui/util/ReaderViewUtil.java:150]: Thank you!

**Review by thomastanck — APPROVED** [review]
Looks Good To Mee
