### PR TITLE
Set CommandResult, Exception & save EntryBook independently of Command

### LINKED ISSUE #34: Design: Decouple updates from command execution
In our discussions, we envision future operations that modify the `Model` outside of command execution, like asynchronous commands that return an initial loading message, fetch data from the Internet, and then return a success or failure message.
However, the current design is unable to support this, so we need to tweak it.
### Problems with current design
With reference to [Remove EventBus issue](https://github.com/se-edu/addressbook-level4/issues/936) in `se-edu/addressbook-level4` and [my forum post](https://github.com/nus-cs2103-AY1819S2/forum/issues/39) in `nus-cs2103-AY1819S2/forum`
#### Saving
`LogicManager#execute(...)` calls `Storage#saveAddressBook(...)`.
This means that `Storage` only saves `AddressBook` when `LogicManager` executes a command, so we need to decouple saving from command execution.
#### Data saving exception
When `LogicManager` calls `Storage#saveAddressBook(...)`, it bubbles any exceptions up to the UI via `CommandException`.
This means that any `CommandException` arising from `Storage` saving `AddressBook` is only thrown when `LogicManager` executes a command, so we need to find a way to propagate storage exceptions to the UI independently of command execution.
#### Displaying command results in UI
`MainWindow#execute(...)` calls `LogicManager#execute(...)`, gets the returned `CommandResult`, then updates the `ResultDisplay` and `CommandBox`.
This means that the UI only updates upon command execution, so we need to decouple UI updates from command execution.

### Possible new designs
Make `Storage` save `AddressBook` whenever it is modified, independently of command execution.

#### Publish-Subscribe Pattern (EventBus, event-driven design)
Follow the previous version of `AddressBook (Level 4)` by implementing the Publish-Subscribe Pattern using Guava's EventBus with a central `EventsCenter`, which publishes `Events` that components like the UI can subscribe to and handle appropriately.

**Pros:**
- Easy to implement

**Cons:**
- Whatever was mentioned in this [issue](https://github.com/se-edu/addressbook-level4/issues/936)
- Unclear dependencies between components
- Pattern not used in `AddressBook (Level 4)`

#### Observer Pattern (JavaFX observable value system)
Extend the Observer Pattern currently implemented in parts of `AddressBook (Level 4)` to make `CommandResult` and `Exception` observable properties in `Model`, which the UI can then observe and update accordingly.

**Pros:**
- Easy to implement
- Pattern used in `AddressBook (Level 4)`

**Cons:**
- `Exception` might not be suitable to be an observable

### PR DESCRIPTION
**Pull request by rlrh**
#### Supports future commands that need to return an initial result first, do some long-running work, and then return another final result or exception, and also internal tasks that modify the model and need to return a user-facing result or exception
- Decouples saving address book from command execution - makes address book save itself to storage whenever it is modified, even if not through command execution
- Makes exception observable and enables it to be manually set (currently used for data-saving exception only)
- Makes manually set command result observable and enables it to be manually set (currently unused)
- Makes UI observe command result and exception and update appropriately, in addition to currently updating on command execution
- Modifies existing tests to support new implementation, adds tests for new capabilities
#### New:
A command can now return an initial command result first, do some long-running task that involves modifying the model, which will save itself to storage, and then update the observable command result or exception, which can then be handled appropriately by the UI.
#### Old:
A command can only return an initial command result, and then do some long-running task that involves modifying the model, but it will not save itself to storage, and a final command result or exception cannot be propagated.
#### How to Use:
In a `Command`'s `execute` method, return an initial `CommandResult`, and within an asynchronous task, set the `Model`'s `commandResultProperty` or `exceptionProperty`.
Example:
```java
Task<Void> task = new Task<>() {
    @Override
    public Void call() throws Exception {
        try {
            Thread.sleep(5000); // some long-running work
            Platform.runLater(() -> {
                model.setCommandResult(new CommandResult(MESSAGE_SUCCESS));
            });
        } catch (Exception e) {
            Platform.runLater(() -> {
                model.setException(new Exception(MESSAGE_FAILURE));
            });
        } finally {
            return null;
        }
    }
};
new Thread(task).start();
return new CommandResult(String.format(MESSAGE_IN_PROGRESS, toAdd));
```

### CODE REVIEW

**Review by thomastanck — APPROVED** [review]

File: src/main/java/seedu/address/ui/CommandBox.java [hunk 1]
```diff
@@ -99,15 +99,29 @@ private void replaceText(String text) {
     private void handleCommandEntered() {
         try {
             commandExecutor.execute(commandTextField.getText());
-            initHistory();
-            historySnapshot.next();
-            commandTextField.setText("");
+            processCommandSuccess();
```
Comment (epicfailname) [inline src/main/java/seedu/address/ui/CommandBox.java:102]: Note to selves that this will be the second time this function is called. The first time is in the line above, within the ```MainWindow```'s ```executeCommand```.
