### PR TITLE
Fix bug where Autofill outputs bad data

### LINKED ISSUE #158: Irrecoverable crash when adding some links
### How to reproduce:
- `add l/https://www.bing.com/s/a/rsslogo.gif`
- You may have to scroll a bit to bring the added entry into rendering range.

### Additional context:

The bug is due to EntryAutofill putting bad data into the description field, which javafx is unable to render.

### PR DESCRIPTION
**Pull request by thomastanck**
Resolves #158.

### Summary of bug and bugfix:

When adding strange entries such as pdf files or
https://www.bing.com/s/a/rsslogo.gif, sometimes autofill puts a lot of
invalid bytes into Description. JavaFX is later unable to display badly
encoded text, so it crashes.

This ensures that autofill ensures that it only fills in ascii-safe
bytes so that javafx will probably be able to display them.

### CODE REVIEW

File: src/main/java/seedu/address/model/entry/util/EntryAutofill.java [hunk 1]
```diff
@@ -86,20 +86,21 @@ public EntryAutofill extractFromHtml(String html) {
             titleCandidate // title 2nd choice - document title element
                     .tryout(document.title().trim());
```
Comment (epicfailname) [inline src/main/java/seedu/address/model/entry/util/EntryAutofill.java]: Do we need to check it here as well?

**Review by epicfailname — APPROVED** [review]
lgtm otherwise

File: src/main/java/seedu/address/model/entry/util/EntryAutofill.java (hunk 1 above)
Comment (thomastanck) [reply src/main/java/seedu/address/model/entry/util/EntryAutofill.java]: Good catch.
